#include "server.h"
#ifndef VALKEYAUDIT_MODULE_VERSION

#define VALKEYAUDIT_VERSION_MAJOR 0
#define VALKEYAUDIT_VERSION_MINOR 0
#define VALKEYAUDIT_VERSION_PATCH 4

#define VALKEYAUDIT_SEMANTIC_VERSION(major, minor, patch) \
  (major * 10000 + minor * 100 + patch)

#define VALKEYAUDIT_MODULE_VERSION VALKEYAUDIT_SEMANTIC_VERSION(VALKEYAUDIT_VERSION_MAJOR, VALKEYAUDIT_VERSION_MINOR, VALKEYAUDIT_VERSION_PATCH)

// Two-level macro expansion to ensure values are substituted before stringification
#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)

// Create the version string using string concatenation
#define VALKEYAUDIT_MODULE_VERSION_STR \
  STRINGIFY(VALKEYAUDIT_VERSION_MAJOR) "." \
  STRINGIFY(VALKEYAUDIT_VERSION_MINOR) "." \
  STRINGIFY(VALKEYAUDIT_VERSION_PATCH)

#endif