#ifndef VALKEYAUDIT_MODULE_VERSION_H
#define VALKEYAUDIT_MODULE_VERSION_H

#define VALKEYAUDIT_VERSION_MAJOR 1
#define VALKEYAUDIT_VERSION_MINOR 0
#define VALKEYAUDIT_VERSION_PATCH 0
#define VALKEYAUDIT_VERSION_RC    1     /* 0 for GA, N for rcN */

/* Encode DEV byte: 0xFF for GA, (RC + 1) for rc candidates */
#if VALKEYAUDIT_VERSION_RC == 0
#define VALKEYAUDIT_VERSION_DEV 0xFF
#else
#define VALKEYAUDIT_VERSION_DEV (VALKEYAUDIT_VERSION_RC + 1)
#endif

#define VALKEYAUDIT_MODULE_VERSION \
    ((VALKEYAUDIT_VERSION_MAJOR << 24) | \
     (VALKEYAUDIT_VERSION_MINOR << 16) | \
     (VALKEYAUDIT_VERSION_PATCH << 8)  | \
     (VALKEYAUDIT_VERSION_DEV))

#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)

#if VALKEYAUDIT_VERSION_RC > 0
#define VALKEYAUDIT_MODULE_VERSION_STR \
    STRINGIFY(VALKEYAUDIT_VERSION_MAJOR) "." \
    STRINGIFY(VALKEYAUDIT_VERSION_MINOR) "." \
    STRINGIFY(VALKEYAUDIT_VERSION_PATCH) "-rc" STRINGIFY(VALKEYAUDIT_VERSION_RC)
#else
#define VALKEYAUDIT_MODULE_VERSION_STR \
    STRINGIFY(VALKEYAUDIT_VERSION_MAJOR) "." \
    STRINGIFY(VALKEYAUDIT_VERSION_MINOR) "." \
    STRINGIFY(VALKEYAUDIT_VERSION_PATCH)
#endif

#endif /* VALKEYAUDIT_MODULE_VERSION_H */
