#ifndef VALKEYAUDIT_MODULE_VERSION_H
#define VALKEYAUDIT_MODULE_VERSION_H

#define VALKEYAUDIT_VERSION_MAJOR 1
#define VALKEYAUDIT_VERSION_MINOR 0
#define VALKEYAUDIT_VERSION_PATCH 0
#define VALKEYAUDIT_VERSION_DEV   0xFF  /* 0x01=dev, 0x02=rc1, 0xFF=GA */

#define VALKEYAUDIT_MODULE_VERSION \
    ((VALKEYAUDIT_VERSION_MAJOR << 24) | \
     (VALKEYAUDIT_VERSION_MINOR << 16) | \
     (VALKEYAUDIT_VERSION_PATCH << 8)  | \
     (VALKEYAUDIT_VERSION_DEV))

#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)

#define VALKEYAUDIT_MODULE_VERSION_STR \
    STRINGIFY(VALKEYAUDIT_VERSION_MAJOR) "." \
    STRINGIFY(VALKEYAUDIT_VERSION_MINOR) "." \
    STRINGIFY(VALKEYAUDIT_VERSION_PATCH)

#endif